//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDemo.DesktopClient.Resources.loginFormContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryDemo.DesktopClient.Resources.loginFormContent.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string strForgottenPassword {
            get {
                return ResourceManager.GetString("strForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid mail..
        /// </summary>
        public static string strInvalidMail {
            get {
                return ResourceManager.GetString("strInvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters: one digit, one special character, one uppercase and one lowercase letter..
        /// </summary>
        public static string strInvalidPassword {
            get {
                return ResourceManager.GetString("strInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string strInvalidUsername {
            get {
                return ResourceManager.GetString("strInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string strInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("strInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string strMail {
            get {
                return ResourceManager.GetString("strMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail is already taken.
        /// </summary>
        public static string strMailNotAvailable {
            get {
                return ResourceManager.GetString("strMailNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail not found.
        /// </summary>
        public static string strMailNotFound {
            get {
                return ResourceManager.GetString("strMailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken.
        /// </summary>
        public static string strNameNotAvailable {
            get {
                return ResourceManager.GetString("strNameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string strRegistration {
            get {
                return ResourceManager.GetString("strRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string strResetPassword {
            get {
                return ResourceManager.GetString("strResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in.
        /// </summary>
        public static string strSingIn {
            get {
                return ResourceManager.GetString("strSingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing up.
        /// </summary>
        public static string strSingUp {
            get {
                return ResourceManager.GetString("strSingUp", resourceCulture);
            }
        }
    }
}
